baseURL = 'https://nyrs.garden/'
languageCode = 'en-us'
title = "Nyrs' garden"
theme = "bonsai"

[params]
user = "[nyrs"
hostname = "home]"
readingTime =true 

  [params.author]
    name = "Nyrs' garden"
    email = "contact@nyrs.garden"

  [[params.social]]
  key = 0
  name = "github"
  url = "https://github.com/Aiclys"

  [[params.social]]
  key = 1
  name = "codeberg"
  url = "https://www.codeberg.org/Nyrs"

  [[params.social]]
  key = 2
  name = "gitlab"
  url = "https://www.gitlab.com/Aiclys"

  [[params.social]]
  key = 3
  name = "email"
  url = "mailto:contact@nyrs.garden"
  Name = "Nyrs"
  HeaderUsername = "welcome"
  HeaderHostname = "nyrs.garden"
  About = "Welcome to my corner of the internet! This is a place for me to share my thoughts on random topics, mostly related to online privacy, philosophy, programming and anything else I find interesting."
[menu]
  [[menu.header]]
    name = "about"
    weight = 0
    url = "/about"

  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts/postsintro"

  [[menu.header]]
    name = "projects"
    weight = 0
    url = "/projects"

  [[menu.header]]
    name = "resources"
    weight = 0
    url = "/resources"
